#!/bin/bash

PLAYER_TEST_DIT=`pwd`
PLAYER_TEST_DIR_EXP_NORMAL="${PLAYER_TEST_DIR}/example_normal"
PLAYER_TEST_DIR_VUE3_VITE="${PLAYER_TEST_DIR}/example_vue3_vite"
PLAYER_TEST_DIR_VUE3="${PLAYER_TEST_DIR}/example_vue3"
PLAYER_TEST_DIR_VUE2="${PLAYER_TEST_DIR}/example_vue2"


rm -rf $PLAYER_TEST_DIR_EXP_NORMAL/dist
cp -r $PLAYER_TEST_DIR_DIST $PLAYER_TEST_DIR_EXP_NORMAL/

rm -rf $PLAYER_TEST_DIR_EXP_NORMAL/dist-multi-thread
cp -r $PLAYER_TEST_DIR_DIST_MULTI $PLAYER_TEST_DIR_EXP_NORMAL/

rm -rf $PLAYER_TEST_DIR_VUE3_VITE/public/dist
cp -r $PLAYER_TEST_DIR_DIST $PLAYER_TEST_DIR_VUE3_VITE/public/dist

rm -rf $PLAYER_TEST_DIR_VUE3/public/dist
cp -r $PLAYER_TEST_DIR_DIST $PLAYER_TEST_DIR_VUE3/public/dist

rm -rf $PLAYER_TEST_DIR_VUE2/public/dist
cp -r $PLAYER_TEST_DIR_DIST $PLAYER_TEST_DIR_VUE2/public/dist
