//
// Created by 小老虎 on 2020/9/26.
//

#ifndef FFMPEG_QUQI_ANALYZER_TE_DEMUXER_COMMON_H
#define FFMPEG_QUQI_ANALYZER_TE_DEMUXER_COMMON_H

#define H265WEBJS_VERSION "v20221120"
#define H265WEBJS_USE_NOT_FREE -1
#define H265WEBJS_USE_FREE 0
#define H265WEBJS_COMPILE_MULTI_THREAD_SHAREDBUFFER 0

#endif //FFMPEG_QUQI_ANALYZER_TE_DEMUXER_COMMON_H
